<a href="https://colab.research.google.com/github/nowhyun/Study/blob/master/%5B%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%EC%9D%84_%EC%9C%84%ED%95%9C_%EC%84%A0%ED%98%95%EB%8C%80%EC%88%98%5D_%EC%8B%A4%EC%8A%B5_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
# column vector
c = np.array([1,2,3])
print(c.shape)

# obtaining a particular entry
print(c[0])

(3,)
1


In [5]:
# row vector
r = np.array([[1,2,3]])
print(r.shape)

# obtaining a aparticular entry
print(r[0,1])

(1, 3)
2


In [7]:
# creating a matrix with all zeors
a = np.zeros((2,2))
print(a)
      
# creating a matrix with all ones
b = np.ones((2,2))
print(b)

# creating a matrix filled with the same constant
c = np.full((2,2), 7)
print(c)

# creating a matrix with random values
d = np.random.random((2,2))
print(d)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0.98053337 0.52740206]
 [0.8225372  0.69333341]]


In [10]:
# creating a matrix
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[11,12,13,14], [15,16,17,18]])
print(A)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[11 12 13 14]
 [15 16 17 18]]


In [9]:
# transpose a matrix
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
# matrix-matrix multiplication
np.dot(A,B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [12]:
# matrix-matrix multiplication
# size should match
np.dot(B,A)

ValueError: ignored

In [14]:
# coefficient matrix A and a vector b
A = np.array(([60, 5.5, 1], [65, 5.0, 0], [55, 6.0, 1]))
b = np.array([66, 70, 78])
print(A)
print(b)

[[60.   5.5  1. ]
 [65.   5.   0. ]
 [55.   6.   1. ]]
[66 70 78]


In [15]:
# identity matrix
eye3 = np.eye(3)
print(eye3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# computing an inverse
from numpy.linalg import inv
A_inv = inv(A)
print(A_inv)

[[ 0.08695652  0.00869565 -0.08695652]
 [-1.13043478  0.08695652  1.13043478]
 [ 2.         -1.         -1.        ]]


In [17]:
# wrong matrix multiplication
# if this operation is matrix multiplication, the the result should be identity matrix
# in this case, * operation is elmentwise multiplication!
A*A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [18]:
# correct matrix multiplication
A.dot(A_inv)

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  1.0000000e+00, -8.8817842e-16],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

In [19]:
# solution of a linear system
# Ax = b => x = A_inv * b
x = A_inv.dot(b)
print(x)

[ -0.43478261  19.65217391 -16.        ]


In [21]:
# a better way to solve the same linear system
# A_inv를 직접적으로 구해야하는 경우는 거의 없다. 이럴 경우 오차가 존재한다.
# solve는 A_inv를 사용하지 않고 구성된다.
from numpy.linalg import solve
x = solve(A,b)
print(x)

[ -0.43478261  19.65217391 -16.        ]
